### POST request to add products to an order - public
POST {{baseUrl}}/public/order
Content-Type: application/json
Cookie: session_id={{sessionId}}

{
  "productId": "66562e3ec8452f39cda8088e",
  "quantity": 1
}

### POST request to add products to an order - auth
POST {{baseUrl}}/auth/order
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "productId": "66562e3ec8452f39cda8088e",
  "quantity": 1
}

### PUT request to remove products from an order - public
PUT {{baseUrl}}/public/order/remove-product/66578a6dcc7f45d177102559
Content-Type: application/json
Cookie: session_id={{sessionId}}

{
  "productId": "66562e3ec8452f39cda8088e"
}

### PUT request to remove products from an order - auth
PUT {{baseUrl}}/auth/order/remove-product/66578a6dcc7f45d177102559
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "productId": "66562e3ec8452f39cda8088e"
}

### PUT request to checkout an order - auth
PUT {{baseUrl}}/auth/order/checkout/66578a6dcc7f45d177102559
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "paymentMethod": "TC",
  "contactNumber": "+573008132438",
  "email": "uribesotod@gmail.com",
  "deliveryAddress": "some delivery address"
}

### PUT request to checkout an order - public
PUT {{baseUrl}}/public/order/checkout/66578a6dcc7f45d177102559
Content-Type: application/json
Cookie: session_id={{sessionId}}

{
  "paymentMethod": "TC",
  "contactNumber": "+573008132438",
  "email": "uribesotod@gmail.com",
  "deliveryAddress": "some delivery address"
}



